config/routes.rb
DSMediaLibrary::Engine.routes.draw do
  root to: redirect { |_, req| req.fullpath + "resources" }
  resources :resources do
    put "", on: :collection, action: :move_many
    delete "", on: :collection, action: :destroy
  end
  resources :folders
end

app/models/ds_media_library/folder.rb
require "awesome_nested_set"
require "ds_node"

module DSMediaLibrary
  class Folder < ActiveRecord::Base
    self.table_name = :folders

    def self.root
      klass = Struct.new(:children, :resources)
      children = Folder.roots.to_a.sort_by(&:name)
      resources = DSNode::Resource.where(folder_id: nil).order(:original_file_name)
      klass.new(children, resources)
    end

    acts_as_nested_set

    has_many :resources, -> { order(:original_file_name) }, class_name: "DSNode::Resource"

    def children
      super.order(:name)
    end

    def all_folders
      self.class.all
    end

    before_destroy :move_all_contents_to_parent!

    private

    def move_all_contents_to_parent!
      transaction do
        resources.each do |resource|
          resource.update! folder: parent
        end
        children.each do |resource|
          resource.update! parent: parent
        end
      end
    end
  end
end

app/controllers/ds_media_library/folders_controller.rb
module DSMediaLibrary
  class FoldersController < ApplicationController
    expose :folder

    def index
      helper = FormHelper::MediaLibrary.from_params(params)
      render "ds_media_library/form_helper/show", locals: { helper: helper}, layout: false
    end

    def new
      @folder = DSMediaLibrary::Folder.new
      render "ds_media_library/manage/folders/form"
    end

    def create
      DSMediaLibrary::Folder.create! folder_params
      redirect_to :resources, notice: "Folder created"
    end

    def edit
      @folder = DSMediaLibrary::Folder.find(params[:id])
      render "ds_media_library/manage/folders/form"
    end

    def update
      DSMediaLibrary::Folder.update params[:id], folder_params
      redirect_to :resources, notice: "Folder updated"
    end

    def destroy
      DSMediaLibrary::Folder.destroy params[:id]
      redirect_to :resources, notice: "Folder deleted"
    end

    private

    def folder_params
      params.require(:folder).permit(:parent_id, :name)
    end
  end
end

app/controllers/ds_media_library/resources_controller.rb
module DSMediaLibrary
  class ResourcesController < ApplicationController
    expose :root, :resource, :folders

    def index
      @root = DSMediaLibrary::Folder.root
      @folders = folders_with_children
      render "ds_media_library/manage/index"
    end

    def new
      @resource = DSNode::Resource.new
      render "ds_media_library/manage/resources/form"
    end

    def create
      resources_params.each do |resource_params|
        DSNode::Resource.create! resource_params
      end
      redirect_to :resources, notice: "Media created"
    end

    def edit
      render "ds_media_library/manage/resources/form"
    end

    def update
      resource.update! resource_params
      redirect_to :resources, notice: "Media updated"
    end

    def destroy
      ids = Array(params[:id]) + Array(params[:resource_ids])
      DSNode::Resource.where(resourcesid: ids).update hidden: true
      redirect_to :resources, notice: "Media deleted"
    end

    def move_many
      DSNode::Resource.where(resourcesid: params[:resource_ids]).update folder_id: params[:folder_id]
      redirect_to :resources, notice: "Media updated"
    end

    private

    def resource
      @resource ||= DSNode::Resource.find(params[:id])
    end

    def folders_with_children
      recurse_folders(DSMediaLibrary::Folder.roots.sort_by(&:name))
    end

    def recurse_folders folders
      folders.flat_map do |folder|
        [folder] + recurse_folders(folder.children)
      end
    end

    def resource_params
      resource_params = params.require(:ds_node_resource).permit(:folder_id, :file)
      # FIXME extract to DSNode gem
      resource_params.merge!(original_file_name: params[:ds_node_resource][:file].original_filename) if params[:ds_node_resource][:file]
      resource_params
    end

    def resources_params
      params[:ds_node_resource][:file].map do |file|
        params.require(:ds_node_resource).permit(:folder_id).merge(file: file)
      end
    end
  end
end

app/helpers/ds_media_library/form_helper.rb
require "active_support/number_helper"

module DSMediaLibrary
  module FormHelper
    def media_library field, label: field.to_s.humanize, multiple: false, optional: false, dimensions: nil, helptext: nil, preview: true, required: false, &block
      selected_ids = Array(object.send(field)).map(&:id)
      helper = MediaLibrary.new(selected_ids, field, label, multiple, optional, dimensions, helptext, preview, required)
      @template.render "ds_media_library/form_helper/media_library_helper", form: self, helper: helper, &block
    end

    class MediaLibrary < Struct.new(:ids, :field, :label, :multiple, :optional, :dimensions, :helptext, :preview, :required)
      def self.from_params params
        new(
          Array(params[:ids] || []).map(&:to_i),
          params[:field],
          params[:label],
          params[:multiple] == "true",
          params[:optional] == "true",
          params[:dimensions],
          params[:helptext],
          params[:preview] == "true",
          params[:required] == "true",
        )
      end

      def selected_resources
        DSNode::Resource.find(ids)
      end

      def single_field
        field.to_s.singularize.to_sym
      end

      def file_field_name
        if multiple
          :"new_#{single_field}_files"
        else
          :"#{field}_file"
        end
      end

      def field_id_name
        if multiple
          :"#{single_field}_ids"
        else
          :"#{field}_id"
        end
      end

      def field_type
        multiple ? "checkbox" : "radio"
      end

      def html_id
        "media-modal-#{field}"
      end

      def label_css_class
        "optional" if optional
      end

      def helptext
        super || dimensions.present? && "#{label.pluralize} must be #{number_with_delimiter(width)}px wide by #{number_with_delimiter(height)}px tall."
      end

      def width
        dimensions.split("x").first if dimensions
      end

      def height
        dimensions.split("x").last if dimensions
      end

      def root
        @root ||= Folder.root
      end

      def root_folders
        root.children
      end

      def root_resources
        root.resources
      end

      private

      def number_with_delimiter number
        ActiveSupport::NumberHelper.number_to_delimited(number)
      end
    end
  end
end

app/views/ds_media_library/_folder.html.slim
li
  input.expand-input type="checkbox" id="#{helper.field}-folder-#{folder.id}"
  .media-container
    label.expand-label.folder-link for="#{helper.field}-folder-#{folder.id}" = folder.name

  - if folder.children.any? || folder.resources.any?
    ul.media-nest
      - with_options locals: { form: form, helper: helper } do |options|
        = options.render collection: folder.children, partial: "ds_media_library/folder", as: :folder
        = options.render collection: folder.resources, partial: "ds_media_library/resource", as: :resource

app/views/ds_media_library/_form_helper.html.slim
.media-library data-media-library=helper.html_id data-media-library-ids=helper.ids required=helper.required
  = form.label helper.file_field_name, helper.label, class: helper.label_css_class

  - if helper.helptext
    .ratio-text = helper.helptext

  label.media-button for=helper.html_id Media library
  em or
  = form.file_field helper.file_field_name, multiple: helper.multiple

  input.modal-input type="checkbox" id=helper.html_id
  .modal-wrapper
    .modal-bg
    .modal-content
      label.modal-close for=helper.html_id
        .borders
      .media-wrapper
        .info-text Choose a media file below to associate with this field.  You can manage media in the <a href="/media_library">Media Library</a>. <br />Note that changing a file in the library will update it across all associated media fields in this app.

        = link_to "Open all folders", "#", class: "open-all-label", data: { "toggle-all-checkboxes" => ".expand-input" }

        input.text#search_media type="text" placeholder="Type keywords to search media (case sensitive)"

        ul.media-nav
          - with_options locals: { form: form, helper: helper } do |options|
            = options.render collection: helper.root_folders, partial: "ds_media_library/folder", as: :folder
            = options.render collection: helper.root_resources, partial: "ds_media_library/resource", as: :resource

  dl.playlist-media id="selected_media_#{helper.html_id}"

app/views/ds_media_library/_resource.html.slim
li.resource class=("hidden" if resource.hidden?)
  .media-container
    label.expand-label
      - if helper.multiple
        input.modal-input.media-choice type="checkbox" value=resource.id checked=form.object.send(helper.field_id_name).include?(resource.id)
      - else
        = form.radio_button helper.field_id_name, resource.id, class: "modal-input media-choice"

      span.media-link alt=resource.original_file_name
        = resource.original_file_name

      script.media-preview-template type="text/x-html-template"
        = render "ds_media_library/image_preview", image: resource, preview: helper.preview do
          - if helper.multiple
            = form.check_box helper.field_id_name, { multiple: true, checked: true }, resource.id, nil
            = form.check_box helper.remove_field_name, { multiple: true }, resource.id, nil
            = form.label :"#{helper.remove_field_name}_#{resource.id}" do
              span Remove #{helper.label.downcase.singularize} {{index}}

          - else
            - if helper.optional
              = form.check_box helper.remove_field_name
              = form.label helper.remove_field_name do
                span Remove #{helper.label.downcase}

          - helper.block.call(resource) if helper.block

app/views/ds_media_library/form_helper/_folder.html.slim
li
  input.dsml-expand-input type="checkbox" id="#{helper.field}-folder-#{folder.id}"
  .dsml-media-container
    label.dsml-expand-label.dsml-folder-link for="#{helper.field}-folder-#{folder.id}" = folder.name

  - if folder.children.any? || folder.resources.any?
    ul.dsml-media-nest
      = render collection: folder.children, partial: "ds_media_library/form_helper/folder", as: :folder, locals: { helper: helper }
      = render collection: folder.resources, partial: "ds_media_library/form_helper/resource", as: :resource, locals: { helper: helper }

app/views/ds_media_library/form_helper/_media_library_helper.html.slim
.media-library data-media-library=helper.html_id data-media-library-ids=helper.ids required=helper.required
  = form.label helper.file_field_name, helper.label, class: helper.label_css_class

  - if helper.helptext
    .ratio-text = helper.helptext

  label.dsml-media-button for=helper.html_id Media library
  em or
  = form.file_field helper.file_field_name, multiple: helper.multiple

  input.dsml-modal-input type="checkbox" id=helper.html_id
  .dsml-modal-wrapper
    .dsml-modal-bg
    .dsml-modal-content
      label.dsml-modal-close for=helper.html_id
        .borders
      .media-wrapper data-load-url=ds_media_library.folders_path(helper.to_h)
        p Loading...
        - helper.selected_resources.each do |resource|
          input.hidden name="ds_media_library" type="checkbox" value=resource.id checked=true data=resource.attributes

  dl.dsml-playlist-media id="dsml-selected-media-#{helper.html_id}"

  script#dsml-media-preview-template type="text/x-html-template"
    dfn.dsml-preview-form
      .dsml-preview-wrapper
        - if helper.preview
          | <{{type}} src="{{url}}" controls=true />

        - if helper.multiple
          = form.hidden_field helper.field_id_name, multiple: true, value: nil
          = form.check_box helper.field_id_name, { multiple: true, checked: true, id: "#{helper.field_id_name}_{{id}}" }, "{{id}}", nil
          label for="#{helper.field_id_name}_{{id}}"
            span Remove #{helper.label.downcase.singularize} {{index}}

        - else
          = form.check_box helper.field_id_name, { checked: true }, "{{id}}", ""
          - if helper.optional
            = form.label helper.field_id_name do
              span Remove #{helper.label.downcase}

        = yield if block_given?

        dt
          figcaption
            | {{#if isPdf}}
            |   <a href="{{url}}" target="_blank" class="dsml-pdf-icon">{{resourcesoriginalfilename}}</a>
            | {{else}}
            |   {{resourcesoriginalfilename}}
            | {{/if}}

app/views/ds_media_library/form_helper/_resource.html.slim
li.dsml-resource class=("hidden" if resource.hidden?) data-dsml-search-text=[resource.original_file_name, resource.type_name, resource.updated_on].join(" ")
  .dsml-media-container
    label.dsml-expand-label
      input.dsml-modal-input.media-choice name="ds_media_library" type=helper.field_type value=resource.id checked=helper.ids.include?(resource.id) data=resource.attributes
      span.dsml-media-link alt=resource.original_file_name = resource.original_file_name
    .dsml-media-type-col = resource.type_name
    .dsml-media-date-col = resource.updated_on

app/views/ds_media_library/form_helper/show.html.slim
.dsml-info-text Choose a media file below to associate with this field.  You can manage media in the <a href="/media_library">Media Library</a>. <br />Note that changing a file in the library will update it across all associated media fields in this app.

= link_to "Open all folders", "#", class: "dsml-open-all-label", data: { "dsml-toggle-all-checkboxes" => ".dsml-expand-input" }

label.hidden for="dsml-search-media" Search media library
input.dsml-text#dsml-search-media type="text" placeholder="Type keywords to search media" data-dsml-search-media=".dsml-resource"
ul.dsml-media-nav#dsml-media-tree
  li.dsml-media-nav-header
    .dsml-media-type-col Type
    .dsml-media-date-col Date modified
  = render collection: helper.root_folders, partial: "ds_media_library/form_helper/folder", as: :folder, locals: { helper: helper }
  = render collection: helper.root_resources, partial: "ds_media_library/form_helper/resource", as: :resource, locals: { helper: helper }

app/views/ds_media_library/resources/_folder.html.slim
li
  input type="checkbox" class="expand-input" id="folder-#{folder.id}"
  .media-container
    label.expand-label.folder-link for="folder-#{folder.id}" = folder.name
    .media-links
      = link_to "Edit folder", [:edit, folder], class: "edit-icon", title: "Edit folder"
      = link_to "Delete folder", folder, method: :delete, class: "delete-icon", title: "Delete folder",
        data: { confirm: "Are you sure you want to delete this folder? This will move any folders and resources it may contain up into its parent folder." }

  - if folder.children.any? || folder.resources.any?
    ul.media-nest
      = render collection: folder.children, partial: "ds_media_library/resources/folder"
      = render collection: folder.resources, partial: "ds_media_library/resources/resource"

app/views/ds_media_library/resources/folder_form.html.slim
= content_for :breadcrumbs do
  ul.breadcrumb-nav
    li = link_to "Media Library", :root
    li
      = folder.new_record? ? "New" : "Edit"
      |  folder


= form_for folder do |form|
  fieldset
    .field
      = form.label :parent_id, "Parent folder", class: "optional"
      = form.collection_select :parent_id, form.object.all_folders, :id, :name, include_blank: " -- none -- "
    .field
      = form.label :name, "Folder name"
      = form.text_field :name, class: "name-input"

  = render "shared/submit", name: "folder"

app/views/ds_media_library/resources/form.html.slim
= content_for :breadcrumbs do
  ul.breadcrumb-nav
    li = link_to "Media Library", :root
    li
      = resource.new_record? ? "New" : "Edit"
      |  media


= form_for resource, url: resource.new_record? ? resources_path : resource_path(resource) do |form|
  fieldset
    .flex
      .field
        .field
          = form.label :folder_id, "Parent folder", class: "optional"
          = form.collection_select :folder_id, DSMediaLibrary::Folder.all, :id, :name, include_blank: " -- none -- "

        -# FIXME extract to super project
        - if form.object.respond_to?(:expires_at)
          .field
            = form.label :expires_at, "Expiration date", class: "optional"
            = form.date_field :expires_at
            .warning-text Expired media items will appear with a <i class="fa fa-exclamation-triangle"></i> icon in the media library and an email will be sent upon expiration as a reminder to update it.

      .field
        = form.label :file, "Upload media"
        = form.file_field :file, multiple: resource.new_record?
        - unless form.object.new_record?
          = render "shared/image_preview", image: form.object

  = render "shared/submit", name: "media"

app/views/ds_media_library/resources/index.html.slim
= content_for :breadcrumbs do
  ul.breadcrumb-nav
    li Media Library

= form_tag nil, method: :put do
  input type="checkbox" id="select-media"
  .table-buttons-flex
    .buttons-left
      = link_to "Open all folders", "#", class: "open-all-label", data: { "toggle-all-checkboxes" => ".expand-input" }
      label.select-media-button for="select-media" Select multiple media
      .field.move-selected
        label.move-selected-label for="folder_id" Move selected to:
        select#folder_id name="folder_id"
          - folders.each do |folder|
            option value=folder.id
              = "- " * folder.depth
              = folder.name
        button.move-button Move

    .buttons-right
      = link_to "Add new folder", [:new, :folder], class: "add-button"
      = link_to "Add new media", [:new, :resource], class: "add-button"

  input.text#search_media type="text" placeholder="Type keywords to search media (case sensitive)"
  ul.media-nav
    = render collection: root.children, partial: "ds_media_library/resources/folder"
    = render collection: root.resources, partial: "ds_media_library/resources/resource"